export const adminstativeConstants = {
  GET_ADMINSTATIVE_REQUEST: "GET_ADMINSTATIVE_REQUEST",
  GET_ADMINSTATIVE_SUCCESS: "GET_ADMINSTATIVE_SUCCESS",
  GET_ADMINSTATIVE_FAILURE: "GET_ADMINSTATIVE_FAILURE",

  UPDATE_ADMINSTATIVE_REQUEST: "UPDATE_ADMINSTATIVE_REQUEST",
  UPDATE_ADMINSTATIVE_SUCCESS: "UPDATE_ADMINSTATIVE_SUCCESS",
  UPDATE_ADMINSTATIVE_FAILURE: "UPDATE_ADMINSTATIVE_FAILURE",
};
