export const channelPartnersConstants = {
    GET_CHANNEL_PARTNERS_REQUEST: "GET_CHANNEL_PARTNERS_REQUEST",
    GET_CHANNEL_PARTNERS_SUCCESS: "GET_CHANNEL_PARTNERS_SUCCESS",
    GET_CHANNEL_PARTNERS_FAILURE: "GET_CHANNEL_PARTNERS_FAILURE",

    CREATE_CHANNEL_PARTNERS_REQUEST: "CREATE_CHANNEL_PARTNERS_REQUEST",
    CREATE_CHANNEL_PARTNERS_SUCCESS: "CREATE_CHANNEL_PARTNERS_SUCCESS",
    CREATE_CHANNEL_PARTNERS_FAILURE: "CREATE_CHANNEL_PARTNERS_FAILURE",

    UPDATE_CHANNEL_PARTNERS_REQUEST: "UPDATE_CHANNEL_PARTNERS_REQUEST",
    UPDATE_CHANNEL_PARTNERS_SUCCESS: "UPDATE_CHANNEL_PARTNERS_SUCCESS",
    UPDATE_CHANNEL_PARTNERS_FAILURE: "UPDATE_CHANNEL_PARTNERS_FAILURE",

    DELETE_CHANNEL_PARTNERS_REQUEST: "DELETE_CHANNEL_PARTNERS_REQUEST",
    DELETE_CHANNEL_PARTNERS_SUCCESS: "DELETE_CHANNEL_PARTNERS_SUCCESS",
    DELETE_CHANNEL_PARTNERS_FAILURE: "DELETE_CHANNEL_PARTNERS_FAILURE",
};
