export const clientManagementConstants = {
    GET_CLIENT_REQUEST: "GET_CLIENT_REQUEST",
    GET_CLIENT_SUCCESS: "GET_CLIENT_SUCCESS",
    GET_CLIENT_FAILURE: "GET_CLIENT_FAILURE",

    CREATE_CLIENT_REQUEST: "CREATE_CLIENT_REQUEST",
    CREATE_CLIENT_SUCCESS: "CREATE_CLIENT_SUCCESS",
    CREATE_CLIENT_FAILURE: "CREATE_CLIENT_FAILURE",

    UPDATE_CLIENT_REQUEST: "UPDATE_CLIENT_REQUEST",
    UPDATE_CLIENT_SUCCESS: "UPDATE_CLIENT_SUCCESS",
    UPDATE_CLIENT_FAILURE: "UPDATE_CLIENT_FAILURE",

    DELETE_CLIENT_REQUEST: "DELETE_CLIENT_REQUEST",
    DELETE_CLIENT_SUCCESS: "DELETE_CLIENT_SUCCESS",
    DELETE_CLIENT_FAILURE: "DELETE_CLIENT_FAILURE",
};
