export const districtManagementConstants = {
  GET_DISTRICT_REQUEST: "GET_DISTRICT_REQUEST",
  GET_DISTRICT_SUCCESS: "GET_DISTRICT_SUCCESS",
  GET_DISTRICT_FAILURE: "GET_DISTRICT_FAILURE",

  CREATE_DISTRICT_REQUEST: "CREATE_DISTRICT_REQUEST",
  CREATE_DISTRICT_SUCCESS: "CREATE_DISTRICT_SUCCESS",
  CREATE_DISTRICT_FAILURE: "CREATE_DISTRICT_FAILURE",

  UPDATE_DISTRICT_REQUEST: "UPDATE_DISTRICT_REQUEST",
  UPDATE_DISTRICT_SUCCESS: "UPDATE_DISTRICT_SUCCESS",
  UPDATE_DISTRICT_FAILURE: "UPDATE_DISTRICT_FAILURE",

  DELETE_DISTRICT_REQUEST: "DELETE_DISTRICT_REQUEST",
  DELETE_DISTRICT_SUCCESS: "DELETE_DISTRICT_SUCCESS",
  DELETE_DISTRICT_FAILURE: "DELETE_DISTRICT_FAILURE",
};
