export const industrySectorConstants = {
  GET_SECTOR_REQUEST: "GET_SECTOR_REQUEST",
  GET_SECTOR_SUCCESS: "GET_SECTOR_SUCCESS",
  GET_SECTOR_FAILURE: "GET_SECTOR_FAILURE",

  CREATE_SECTOR_REQUEST: "CREATE_SECTOR_REQUEST",
  CREATE_SECTOR_SUCCESS: "CREATE_SECTOR_SUCCESS",
  CREATE_SECTOR_FAILURE: "CREATE_SECTOR_FAILURE",

  UPDATE_SECTOR_REQUEST: "UPDATE_SECTOR_REQUEST",
  UPDATE_SECTOR_SUCCESS: "UPDATE_SECTOR_SUCCESS",
  UPDATE_SECTOR_FAILURE: "UPDATE_SECTOR_FAILURE",

  DELETE_SECTOR_REQUEST: "DELETE_SECTOR_REQUEST",
  DELETE_SECTOR_SUCCESS: "DELETE_SECTOR_SUCCESS",
  DELETE_SECTOR_FAILURE: "DELETE_SECTOR_FAILURE",
};
