export const membershipConstants = {
    GET_MEMBERSHIP_REQUEST: "GET_MEMBERSHIP_REQUEST",
    GET_MEMBERSHIP_SUCCESS: "GET_MEMBERSHIP_SUCCESS",
    GET_MEMBERSHIP_FAILURE: "GET_MEMBERSHIP_FAILURE",

    CREATE_MEMBERSHIP_REQUEST: "CREATE_MEMBERSHIP_REQUEST",
    CREATE_MEMBERSHIP_SUCCESS: "CREATE_MEMBERSHIP_SUCCESS",
    CREATE_MEMBERSHIP_FAILURE: "CREATE_MEMBERSHIP_FAILURE",

    UPDATE_MEMBERSHIP_REQUEST: "UPDATE_MEMBERSHIP_REQUEST",
    UPDATE_MEMBERSHIP_SUCCESS: "UPDATE_MEMBERSHIP_SUCCESS",
    UPDATE_MEMBERSHIP_FAILURE: "UPDATE_MEMBERSHIP_FAILURE",

    DELETE_MEMBERSHIP_REQUEST: "DELETE_MEMBERSHIP_REQUEST",
    DELETE_MEMBERSHIP_SUCCESS: "DELETE_MEMBERSHIP_SUCCESS",
    DELETE_MEMBERSHIP_FAILURE: "DELETE_MEMBERSHIP_FAILURE",
};
