export const reportManagementConstants = {
  GET_REPORTS_BASED_ON_USER_REQUEST: "GET_REPORTS_BASED_ON_USER_REQUEST",
  GET_REPORTS_BASED_ON_USER_SUCCESS: "GET_REPORTS_BASED_ON_USER_SUCCESS",
  GET_REPORTS_BASED_ON_USER_FAILURE: "GET_REPORTS_BASED_ON_USER_FAILURE",
};
