export const stateManagementConstants = {
  GET_STATE_REQUEST: "GET_STATE_REQUEST",
  GET_STATE_SUCCESS: "GET_STATE_SUCCESS",
  GET_STATE_FAILURE: "GET_STATE_FAILURE",

  CREATE_STATE_REQUEST: "CREATE_STATE_REQUEST",
  CREATE_STATE_SUCCESS: "CREATE_STATE_SUCCESS",
  CREATE_STATE_FAILURE: "CREATE_STATE_FAILURE",

  UPDATE_STATE_REQUEST: "UPDATE_STATE_REQUEST",
  UPDATE_STATE_SUCCESS: "UPDATE_STATE_SUCCESS",
  UPDATE_STATE_FAILURE: "UPDATE_STATE_FAILURE",

  DELETE_STATE_REQUEST: "DELETE_STATE_REQUEST",
  DELETE_STATE_SUCCESS: "DELETE_STATE_SUCCESS",
  DELETE_STATE_FAILURE: "DELETE_STATE_FAILURE",
};
