export const subsidyManagementConstants = {
  GET_SUBSIDY_REQUEST: "GET_SUBSIDY_REQUEST",
  GET_SUBSIDY_SUCCESS: "GET_SUBSIDY_SUCCESS",
  GET_SUBSIDY_FAILURE: "GET_SUBSIDY_FAILURE",

  CREATE_SUBSIDY_REQUEST: "CREATE_SUBSIDY_REQUEST",
  CREATE_SUBSIDY_SUCCESS: "CREATE_SUBSIDY_SUCCESS",
  CREATE_SUBSIDY_FAILURE: "CREATE_SUBSIDY_FAILURE",

  UPDATE_SUBSIDY_REQUEST: "UPDATE_SUBSIDY_REQUEST",
  UPDATE_SUBSIDY_SUCCESS: "UPDATE_SUBSIDY_SUCCESS",
  UPDATE_SUBSIDY_FAILURE: "UPDATE_SUBSIDY_FAILURE",

  DELETE_SUBSIDY_REQUEST: "DELETE_SUBSIDY_REQUEST",
  DELETE_SUBSIDY_SUCCESS: "DELETE_SUBSIDY_SUCCESS",
  DELETE_SUBSIDY_FAILURE: "DELETE_SUBSIDY_FAILURE",
};
