export const subsidyManagementConstants = {
  GET_SUBSIDY_REQUEST: "GET_SUBSIDY_REQUEST",
  GET_SUBSIDY_SUCCESS: "GET_SUBSIDY_SUCCESS",
  GET_SUBSIDY_FAILURE: "GET_SUBSIDY_FAILURE",

  CREATE_SUBSIDY_REQUEST: "CREATE_SUBSIDY_REQUEST",
  CREATE_SUBSIDY_SUCCESS: "CREATE_SUBSIDY_SUCCESS",
  CREATE_SUBSIDY_FAILURE: "CREATE_SUBSIDY_FAILURE",

  DELETE_SUBSIDY_REQUEST: "DELETE_SUBSIDY_REQUEST",
  DELETE_SUBSIDY_SUCCESS: "DELETE_SUBSIDY_SUCCESS",
  DELETE_SUBSIDY_FAILURE: "DELETE_SUBSIDY_FAILURE",

  GET_SUBSIDY_DETAILS_REQUEST: "GET_SUBSIDY_DETAILS_REQUEST",
  GET_SUBSIDY_DETAILS_SUCCESS: "GET_SUBSIDY_DETAILS_SUCCESS",
  GET_SUBSIDY_DETAILS_FAILURE: "GET_SUBSIDY_DETAILS_FAILURE",

  REMOVE_SUBSIDY_DETAILS_SUCCESS: "REMOVE_SUBSIDY_DETAILS_SUCCESS",

  REMOVE_SUBSIDY_DETAILS_QUESTION_SUCCESS:
    "REMOVE_SUBSIDY_DETAILS_QUESTION_SUCCESS",

  CREATE_CONSTANT_REQUEST: "CREATE_CONSTANT_REQUEST",
  CREATE_CONSTANT_SUCCESS: "CREATE_CONSTANT_SUCCESS",
  CREATE_CONSTANT_FAILURE: "CREATE_CONSTANT_FAILURE",

  GET_CONSTANT_REQUEST: "GET_CONSTANT_REQUEST",
  GET_CONSTANT_SUCCESS: "GET_CONSTANT_SUCCESS",
  GET_CONSTANT_FAILURE: "GET_CONSTANT_FAILURE",

  ADD_CONSTANT_TO_SUBSIDY_REQUEST: "ADD_CONSTANT_TO_SUBSIDY_REQUEST",
  ADD_CONSTANT_TO_SUBSIDY_SUCCESS: "ADD_CONSTANT_TO_SUBSIDY_SUCCESS",
  ADD_CONSTANT_TO_SUBSIDY_FAILURE: "ADD_CONSTANT_TO_SUBSIDY_FAILURE",

  GET_USER_INPUT_FIELD_NAME_REQUEST: "GET_USER_INPUT_FIELD_NAME_REQUEST",
  GET_USER_INPUT_FIELD_NAME_SUCCESS: "GET_USER_INPUT_FIELD_NAME_SUCCESS",
  GET_USER_INPUT_FIELD_NAME_FAILURE: "GET_USER_INPUT_FIELD_NAME_FAILURE",

  CREATE_USER_INPUT_REQUEST: "CREATE_USER_INPUT_REQUEST",
  CREATE_USER_INPUT_SUCCESS: "CREATE_USER_INPUT_SUCCESS",
  CREATE_USER_INPUT_FAILURE: "CREATE_USER_INPUT_FAILURE",

  GET_USER_INPUT_REQUEST: "GET_USER_INPUT_REQUEST",
  GET_USER_INPUT_SUCCESS: "GET_USER_INPUT_SUCCESS",
  GET_USER_INPUT_FAILURE: "GET_USER_INPUT_FAILURE",

  GET_CONSTANT_TO_A_SUBSIDY_REQUEST: "GET_CONSTANT_TO_A_SUBSIDY_REQUEST",
  GET_CONSTANT_TO_A_SUBSIDY_SUCCESS: "GET_CONSTANT_TO_A_SUBSIDY_SUCCESS",
  GET_CONSTANT_TO_A_SUBSIDY_FAILURE: "GET_CONSTANT_TO_A_SUBSIDY_FAILURE",

  CREATE_SUBSIDY_CONDITION_REQUEST: "CREATE_SUBSIDY_CONDITION_REQUEST",
  CREATE_SUBSIDY_CONDITION_SUCCESS: "CREATE_SUBSIDY_CONDITION_SUCCESS",
  CREATE_SUBSIDY_CONDITION_FAILURE: "CREATE_SUBSIDY_CONDITION_FAILURE",

  GET_CONDITION_REQUEST: "GET_CONDITION_REQUEST",
  GET_CONDITION_SUCCESS: "GET_CONDITION_SUCCESS",
  GET_CONDITION_FAILURE: "GET_CONDITION_FAILURE",

  UPDATE_SUBSIDY_CONDITION_REQUEST: "UPDATE_SUBSIDY_CONDITION_REQUEST",
  UPDATE_SUBSIDY_CONDITION_SUCCESS: "UPDATE_SUBSIDY_CONDITION_SUCCESS",
  UPDATE_SUBSIDY_CONDITION_FAILURE: "UPDATE_SUBSIDY_CONDITION_FAILURE",

  DELETE_SUBSIDY_CONDITION_REQUEST: "DELETE_SUBSIDY_CONDITION_REQUEST",
  DELETE_SUBSIDY_CONDITION_SUCCESS: "DELETE_SUBSIDY_CONDITION_SUCCESS",
  DELETE_SUBSIDY_CONDITION_FAILURE: "DELETE_SUBSIDY_CONDITION_FAILURE",

  GET_MATCHING_CRITERIA_REQUEST: "GET_MATCHING_CRITERIA_REQUEST",
  GET_MATCHING_CRITERIA_SUCCESS: "GET_MATCHING_CRITERIA_SUCCESS",
  GET_MATCHING_CRITERIA_FAILURE: "GET_MATCHING_CRITERIA_FAILURE",

  GET_QUESTION_FOR_A_SUBSIDY_REQUEST: "GET_QUESTION_FOR_A_SUBSIDY_REQUEST",
  GET_QUESTION_FOR_A_SUBSIDY_SUCCESS: "GET_QUESTION_FOR_A_SUBSIDY_SUCCESS",
  GET_QUESTION_FOR_A_SUBSIDY_FAILURE: "GET_QUESTION_FOR_A_SUBSIDY_FAILURE",

  CREATE_MATCHING_CRITERIA_REQUEST: "CREATE_MATCHING_CRITERIA_REQUEST",
  CREATE_MATCHING_CRITERIA_SUCCESS: "CREATE_MATCHING_CRITERIA_SUCCESS",
  CREATE_MATCHING_CRITERIA_FAILURE: "CREATE_MATCHING_CRITERIA_FAILURE",

  DELETE_MATCHING_CRITERIA_REQUEST: "DELETE_MATCHING_CRITERIA_REQUEST",
  DELETE_MATCHING_CRITERIA_SUCCESS: "DELETE_MATCHING_CRITERIA_SUCCESS",
  DELETE_MATCHING_CRITERIA_FAILURE: "DELETE_MATCHING_CRITERIA_FAILURE",
};
