export const subsidyManagementConstants = {
  GET_SUBSIDY_REQUEST: "GET_SUBSIDY_REQUEST",
  GET_SUBSIDY_SUCCESS: "GET_SUBSIDY_SUCCESS",
  GET_SUBSIDY_FAILURE: "GET_SUBSIDY_FAILURE",

  CREATE_SUBSIDY_REQUEST: "CREATE_SUBSIDY_REQUEST",
  CREATE_SUBSIDY_SUCCESS: "CREATE_SUBSIDY_SUCCESS",
  CREATE_SUBSIDY_FAILURE: "CREATE_SUBSIDY_FAILURE",

  GET_SUBSIDY_DETAILS_REQUEST: "GET_SUBSIDY_DETAILS_REQUEST",
  GET_SUBSIDY_DETAILS_SUCCESS: "GET_SUBSIDY_DETAILS_SUCCESS",
  GET_SUBSIDY_DETAILS_FAILURE: "GET_SUBSIDY_DETAILS_FAILURE",

  CREATE_CONSTANT_REQUEST: "CREATE_CONSTANT_REQUEST",
  CREATE_CONSTANT_SUCCESS: "CREATE_CONSTANT_SUCCESS",
  CREATE_CONSTANT_FAILURE: "CREATE_CONSTANT_FAILURE",

  GET_CONSTANT_REQUEST: "GET_CONSTANT_REQUEST",
  GET_CONSTANT_SUCCESS: "GET_CONSTANT_SUCCESS",
  GET_CONSTANT_FAILURE: "GET_CONSTANT_FAILURE",

  ADD_CONSTANT_TO_SUBSIDY_REQUEST: "ADD_CONSTANT_TO_SUBSIDY_REQUEST",
  ADD_CONSTANT_TO_SUBSIDY_SUCCESS: "ADD_CONSTANT_TO_SUBSIDY_SUCCESS",
  ADD_CONSTANT_TO_SUBSIDY_FAILURE: "ADD_CONSTANT_TO_SUBSIDY_FAILURE",

  GET_USER_INPUT_FIELD_NAME_REQUEST: "GET_USER_INPUT_FIELD_NAME_REQUEST",
  GET_USER_INPUT_FIELD_NAME_SUCCESS: "GET_USER_INPUT_FIELD_NAME_SUCCESS",
  GET_USER_INPUT_FIELD_NAME_FAILURE: "GET_USER_INPUT_FIELD_NAME_FAILURE",

  CREATE_USER_INPUT_REQUEST: "CREATE_USER_INPUT_REQUEST",
  CREATE_USER_INPUT_SUCCESS: "CREATE_USER_INPUT_SUCCESS",
  CREATE_USER_INPUT_FAILURE: "CREATE_USER_INPUT_FAILURE",

  GET_USER_INPUT_REQUEST: "GET_USER_INPUT_REQUEST",
  GET_USER_INPUT_SUCCESS: "GET_USER_INPUT_SUCCESS",
  GET_USER_INPUT_FAILURE: "GET_USER_INPUT_FAILURE",

  GET_CONSTANT_TO_A_SUBSIDY_REQUEST: "GET_CONSTANT_TO_A_SUBSIDY_REQUEST",
  GET_CONSTANT_TO_A_SUBSIDY_SUCCESS: "GET_CONSTANT_TO_A_SUBSIDY_SUCCESS",
  GET_CONSTANT_TO_A_SUBSIDY_FAILURE: "GET_CONSTANT_TO_A_SUBSIDY_FAILURE",
};
