export const talukaManagementConstants = {
  GET_TALUKA_REQUEST: "GET_TALUKA_REQUEST",
  GET_TALUKA_SUCCESS: "GET_TALUKA_SUCCESS",
  GET_TALUKA_FAILURE: "GET_TALUKA_FAILURE",

  CREATE_TALUKA_REQUEST: "CREATE_TALUKA_REQUEST",
  CREATE_TALUKA_SUCCESS: "CREATE_TALUKA_SUCCESS",
  CREATE_TALUKA_FAILURE: "CREATE_TALUKA_FAILURE",

  UPDATE_TALUKA_REQUEST: "UPDATE_TALUKA_REQUEST",
  UPDATE_TALUKA_SUCCESS: "UPDATE_TALUKA_SUCCESS",
  UPDATE_TALUKA_FAILURE: "UPDATE_TALUKA_FAILURE",

  DELETE_TALUKA_REQUEST: "DELETE_TALUKA_REQUEST",
  DELETE_TALUKA_SUCCESS: "DELETE_TALUKA_SUCCESS",
  DELETE_TALUKA_FAILURE: "DELETE_TALUKA_FAILURE",
};
