export const trustedPartnersConstants = {
    GET_TRUSTED_PARTNERS_REQUEST: "GET_TRUSTED_PARTNERS_REQUEST",
    GET_TRUSTED_PARTNERS_SUCCESS: "GET_TRUSTED_PARTNERS_SUCCESS",
    GET_TRUSTED_PARTNERS_FAILURE: "GET_TRUSTED_PARTNERS_FAILURE",

    GET_SINGLE_TRUSTED_PARTNER_REQUEST: "GET_SINGLE_TRUSTED_PARTNER_REQUEST",
    GET_SINGLE_TRUSTED_PARTNER_SUCCESS: "GET_SINGLE_TRUSTED_PARTNER_SUCCESS",
    GET_SINGLE_TRUSTED_PARTNER_FAILURE: "GET_SINGLE_TRUSTED_PARTNER_FAILURE",


    CREATE_TRUSTED_PARTNERS_REQUEST: "CREATE_TRUSTED_PARTNERS_REQUEST",
    CREATE_TRUSTED_PARTNERS_SUCCESS: "CREATE_TRUSTED_PARTNERS_SUCCESS",
    CREATE_TRUSTED_PARTNERS_FAILURE: "CREATE_TRUSTED_PARTNERS_FAILURE",

    UPDATE_TRUSTED_PARTNERS_REQUEST: "UPDATE_TRUSTED_PARTNERS_REQUEST",
    UPDATE_TRUSTED_PARTNERS_SUCCESS: "UPDATE_TRUSTED_PARTNERS_SUCCESS",
    UPDATE_TRUSTED_PARTNERS_FAILURE: "UPDATE_TRUSTED_PARTNERS_FAILURE",

    DELETE_TRUSTED_PARTNERS_REQUEST: "DELETE_TRUSTED_PARTNERS_REQUEST",
    DELETE_TRUSTED_PARTNERS_SUCCESS: "DELETE_TRUSTED_PARTNERS_SUCCESS",
    DELETE_TRUSTED_PARTNERS_FAILURE: "DELETE_TRUSTED_PARTNERS_FAILURE",
};
