export const userConstants = {
  USER_LOGIN_REQUEST: "USER_LOGIN_REQUEST",
  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_LOGIN_FAILURE: "USER_LOGIN_FAILURE",

  USER_SET_CREDENTIALS: "USER_SET_CREDENTIALS",

  LOGOUT: "LOGOUT",
};
